#!/usr/bin/env python3
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

"""Generates iceoryx2-ffi/c/src/api/guarded.rs: an iox2_guarded_* twin for
every exported FFI function that catches unwinding panics and returns a
sentinel instead of aborting the process.

Run from the repository root after a submodule bump (the submodule must
already carry the extern "C-unwind" ABI conversion and panic = "unwind"
profile from the csharp-panic-containment branch):

    python scripts/generate_panic_guards.py

Functions whose return type has no safe sentinel (by-value enums) are
skipped and listed; the C# binding keeps calling those directly.
"""

import re
import sys
from pathlib import Path

FFI_SRC = Path(__file__).resolve().parent.parent / "iceoryx2" / "iceoryx2-ffi" / "c" / "src"
OUTPUT = FFI_SRC / "api" / "guarded.rs"

FN_PATTERN = re.compile(r'pub (?:unsafe )?extern "C-unwind" fn (iox2_\w+)\(')

INT_TYPES = {"usize", "isize", "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64", "c_size_t"}


def matching_paren(text: str, start: int) -> int:
    """Index of the ')' matching the '(' at text[start]."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("unbalanced parens")


def split_args(arg_text: str) -> list[tuple[str, str]]:
    """Top-level comma split of 'name: Type' pairs."""
    args, depth, current = [], 0, []
    for ch in arg_text:
        if ch in "(<[":
            depth += 1
        elif ch in ")>]":
            depth -= 1
        if ch == "," and depth == 0:
            args.append("".join(current))
            current = []
        else:
            current.append(ch)
    if "".join(current).strip():
        args.append("".join(current))
    pairs = []
    for arg in args:
        name, type_ = arg.split(":", 1)
        name = name.strip()
        if name.startswith("mut "):
            name = name[4:]
        pairs.append((name, type_.strip()))
    return pairs


def sentinel(ret: str) -> str | None:
    """Sentinel expression for a return type; None means unguardable."""
    if ret == "":
        return "()"
    if ret == "c_int":
        return "-1"
    if ret == "bool":
        return "false"
    if ret in INT_TYPES:
        return "0"
    if ret.startswith("*") or re.fullmatch(r"iox2_\w+(_h|_h_ref|_ptr|_ptr_mut)", ret):
        return "unsafe { core::mem::zeroed() }"
    return None


def collect_functions() -> tuple[list[dict], list[str]]:
    functions, skipped = [], []
    for path in sorted(FFI_SRC.rglob("*.rs")):
        if path == OUTPUT:
            continue
        text = path.read_text(encoding="utf-8")
        for match in FN_PATTERN.finditer(text):
            name = match.group(1)
            open_paren = match.end() - 1
            close_paren = matching_paren(text, open_paren)
            arg_text = text[open_paren + 1 : close_paren]
            rest = text[close_paren + 1 : text.index("{", close_paren)]
            ret = rest.replace("->", "", 1).strip() if "->" in rest else ""
            sent = sentinel(ret)
            if sent is None:
                skipped.append(f"{name} -> {ret}")
                continue
            functions.append({
                "name": name,
                "module": path.stem,
                "args": split_args(arg_text),
                "arg_text": " ".join(arg_text.split()),
                "ret": ret,
                "sentinel": sent,
            })
    return functions, skipped


PRELUDE = '''// Copyright (c) 2025 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

// GENERATED by scripts/generate_panic_guards.py - do not edit by hand.
//
// Panic containment for host-language bindings: every exported FFI function
// has an iox2_guarded_* twin that catches unwinding panics, records the
// panic message, notifies an optional host callback, and returns a sentinel
// (-1 / null / false / 0) instead of aborting the process. Requires
// panic = "unwind" and the extern "C-unwind" ABI on the wrapped functions.

#![allow(clippy::missing_safety_doc)]
#![allow(unused_imports)]

// MODULE_IMPORTS
use crate::*;
use super::*;
use core::ffi::{c_char, c_int, c_void};
use std::cell::RefCell;
use std::ffi::CString;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Once;

type PanicCallback = extern "C" fn(*const c_char);

static PANIC_CALLBACK: AtomicUsize = AtomicUsize::new(0);
static HOOK_INIT: Once = Once::new();

thread_local! {
    static LAST_PANIC: RefCell<Option<CString>> = const { RefCell::new(None) };
}

fn init_panic_capture() {
    HOOK_INIT.call_once(|| {
        let previous = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            let message = info.to_string().replace('\\0', " ");
            let c_message =
                CString::new(message).unwrap_or_else(|_| CString::new("panic").expect("static"));
            let cb = PANIC_CALLBACK.load(Ordering::Acquire);
            if cb != 0 {
                let cb: PanicCallback = unsafe { core::mem::transmute(cb) };
                cb(c_message.as_ptr());
            }
            LAST_PANIC.with(|slot| *slot.borrow_mut() = Some(c_message));
            previous(info);
        }));
    });
}

/// Registers a callback invoked with the panic message whenever a panic is
/// caught anywhere in the library. The callback runs on the panicking thread
/// and must not call back into iceoryx2 or throw.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn iox2_guarded_set_panic_callback(callback: Option<PanicCallback>) {
    init_panic_capture();
    PANIC_CALLBACK.store(callback.map(|c| c as usize).unwrap_or(0), Ordering::Release);
}

/// Copies the calling thread's last caught panic message into `buffer`
/// (NUL-terminated, truncated to `buffer_len`) and clears it. Returns false
/// when no panic is pending.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn iox2_guarded_take_last_panic(
    buffer: *mut c_char,
    buffer_len: usize,
) -> bool {
    LAST_PANIC.with(|slot| match slot.borrow_mut().take() {
        Some(message) => {
            if !buffer.is_null() && buffer_len > 0 {
                let bytes = message.as_bytes_with_nul();
                let n = bytes.len().min(buffer_len);
                unsafe {
                    core::ptr::copy_nonoverlapping(bytes.as_ptr() as *const c_char, buffer, n);
                    *buffer.add(n - 1) = 0;
                }
            }
            true
        }
        None => false,
    })
}
'''


def emit(functions: list[dict]) -> str:
    # Functions in api/mod.rs live directly in crate::api ("mod" is a keyword).
    modules = sorted({f["module"] for f in functions} - {"mod"})
    imports = "\n".join(f"use crate::api::{m}::*;" for m in modules)
    parts = [PRELUDE.replace("// MODULE_IMPORTS", imports)]
    for f in functions:
        short = f["name"][len("iox2_"):]
        ret_clause = f" -> {f['ret']}" if f["ret"] else ""
        call_args = ", ".join(name for name, _ in f["args"])
        module_path = "crate::api" if f["module"] == "mod" else f"crate::api::{f['module']}"
        body_call = f"unsafe {{ {module_path}::{f['name']}({call_args}) }}"
        parts.append(
            f"""
#[unsafe(no_mangle)]
pub unsafe extern "C" fn iox2_guarded_{short}({f['arg_text']}){ret_clause} {{
    init_panic_capture();
    match std::panic::catch_unwind(core::panic::AssertUnwindSafe(|| {body_call})) {{
        Ok(value) => value,
        Err(_) => {f['sentinel']},
    }}
}}
"""
        )
    return "".join(parts)


def main() -> int:
    functions, skipped = collect_functions()
    OUTPUT.write_text(emit(functions), encoding="utf-8", newline="\n")
    print(f"wrapped: {len(functions)} functions -> {OUTPUT}")
    if skipped:
        print(f"skipped ({len(skipped)}, no safe sentinel):")
        for s in skipped:
            print(f"  {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
